# Generated by Django 5.0.7 on 2024-12-18 16:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_friendslist_friend_alter_friendslist_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendslist",
            unique_together={("user", "friend")},
        ),
    ]
