# Generated by Django 5.1.3 on 2024-12-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movies',
            index=models.Index(fields=['title', 'release_date', 'country', 'poster', 'average_rating'], name='basic_site__title_d64788_idx'),
        ),
    ]
