# Generated by Django 5.1.3 on 2024-12-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0002_movies_basic_site__title_d64788_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
