# Generated by Django 5.1.3 on 2024-12-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0002_categories_movies_comments_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='Genres',
        ),
        migrations.RenameField(
            model_name='movies',
            old_name='category',
            new_name='genres',
        ),
    ]
