# Generated by Django 5.0.7 on 2024-12-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0003_alter_comments_content_alter_genres_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='csv_filename',
            field=models.FileField(blank=True, null=True, upload_to='movie_csv/'),
        ),
    ]
