# Generated by Django 5.1.3 on 2024-12-03 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0004_alter_comments_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='basic_site.movies'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='basic_site.genres'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='basic_site.movies'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
