# Generated by Django 5.0.7 on 2024-12-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0004_movies_csv_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCSV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_filename', models.FileField(blank=True, null=True, upload_to='movie_csv/')),
            ],
        ),
        migrations.RemoveField(
            model_name='movies',
            name='csv_filename',
        ),
    ]
