# Generated by Django 5.1.3 on 2024-12-03 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0005_alter_comments_movie_alter_movies_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='poster',
            field=models.TextField(default='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<django.db.models.fields.DateField>'),
        ),
        migrations.AddField(
            model_name='movies',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
