# Generated by Django 5.1.3 on 2024-12-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0006_movies_poster_movies_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.TextField(blank=True),
        ),
    ]
