# Generated by Django 5.0.7 on 2024-12-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_site", "0007_alter_friendslist_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendslist",
            name="added_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="friendslist",
            name="is_friend",
            field=models.BooleanField(default=False),
        ),
    ]
