# Generated by Django 5.0.7 on 2024-12-22 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("basic_site", "0008_friendslist_added_at_friendslist_is_friend"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlater",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlater",
                to="basic_site.movies",
            ),
        ),
        migrations.AlterField(
            model_name="watchlater",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watchlater",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
