# Generated by Django 5.1.3 on 2024-12-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_site', '0010_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
